### ISSUE TITLE
ERROR: Version in "docker-compose.yaml" is unsupported

### ISSUE THREAD

**Issue by droter** [hadabot/hadabot_main#1]
Hi,

Thanks for putting this together.

I tried running the container and I am getting this error:
$ docker-compose up -d
/home/matt/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

$ docker --version
Docker version 18.09.7, build 2d0083d

$ docker-compose --version
docker-compose version 1.8.0, build unknown

Am I running the wrong version of docker?

**Comment by jackpien** [comment]
Hi @droter - you might want to try to upgrade your docker and docker-compose

Here's my versions

$ docker-compose -v
docker-compose version 1.25.4, build 8d51620a
(pelican_3) jpien@chandler:~/local/projects/hadabot/gitspace/hadabot_blog_v1
$ docker -v
Docker version 19.03.5, build 633a0ea

Will make closed unless upgrading still doesn't work.
