### ISSUE TITLE
theta_rad from orientation in update_odometry()

### ISSUE THREAD

**Issue by dsryzhov** [hadabot/hadabot_main#12]
Hi Jack,

In update_odometry theta_rad is set incorrect
https://github.com/hadabot/hadabot_main/blob/master/content/p7/hadabot_ws/src/hadabot_driver/src/hadabot_controller.cpp

auto theta_rad = pose_->pose.pose.orientation.z;

Correct procedure is
    tf2::Quaternion q0(pose_->pose.pose.orientation.x, pose_->pose.pose.orientation.y, pose_->pose.pose.orientation.z, pose_->pose.pose.orientation.w);
    tf2::Matrix3x3 m(q0);
    double roll, pitch, yaw;
    m.getRPY(roll, pitch, yaw);
    double theta_rad = yaw;

In constructor initial orientation should be initialized from Euler angles
    tf2::Quaternion q;
    q.setEuler(0,0,0);
    pose_->pose.pose.orientation.x  = q.getX();
    pose_->pose.pose.orientation.y  = q.getY();
    pose_->pose.pose.orientation.z  = q.getZ();
    pose_->pose.pose.orientation.w  = q.getW();

Regards,
Dmitry

**Comment by jackpien** [comment]
Good catch @dsryzhov !

Also, like with Issue #9, the d_left_m and d_right_m is incorrectly dividing by PI. I will fix that along with the theta_rad fix.

BTW - if you'd like, you can fork this repo, make changes to fix issues, then submit a Pull Request. This way you don't have to cut-n-paste code into a new Issue. Happy to walk you through process if you'd like, just drop me email. Thx!! Jack
