### ISSUE TITLE
WWW - Setup ESP32 Flash MicroPython clearer instructions.

### ISSUE THREAD

**Issue by Luke-Ferderer** [hadabot/hadabot_main#20]
In step 5 of [Setup ESP32 Flash MicroPython](https://www.hadabot.com/setup-esp32-flash-micropython.html), a small bit of text that pointed to where the drop down menu is to change the Baud rate would be helpful. Also, it might be good to explain what Baud is.

Pictures for what the website should look like after step 10 and 11 might help. Something like this:
![image](https://user-images.githubusercontent.com/59193903/137675329-0e40858c-0579-4f0f-9249-cf236ae68e9b.png)

**Comment by jackpien** [comment]
WWW updated with suggested clarifications
