### ISSUE TITLE
WWW - Hiding network password during firmware file bundle upload

### ISSUE THREAD

**Issue by Luke-Ferderer** [hadabot/hadabot_main#21]
On the page [Setup ESP32 Upload Hadabot File Bundle](https://www.hadabot.com/setup-esp32-upload-file-bundle.html) I feel that the network password should be hidden as users enter it. Improves privacy if being used in a public space.

**Comment by jackpien** [comment]
When form is changed to "password" type (which hides the password), the browsers will always request to "save the password" which is not relevant in this application. SSID passwords are generally pretty low risk so think it's ok. Even if in a public space, you are going to assign the pwd for the public SSID WiFi so everyone will know it anyway. Will not change for now unless a more compelling reason comes up.
