### ISSUE TITLE
Getting error with GPG in docker -compose up

### ISSUE THREAD

**Issue by Snorlax104** [hadabot/hadabot_main#30]
I have been trying to do docker -compose up but I am getting this error. I tried all the stuff out there but I was not able to solve it. Can someone please help.

![image](https://user-images.githubusercontent.com/97780276/225916212-92f43f5f-5c4a-4730-8d75-85c519a83c33.png)

**Comment by the-observer07** [comment]
i too have experienced this. any luck?

**Comment by the-observer07** [comment]
https://github.com/hadabot/hadabot_main/pull/26/files

@Snorlax104 this is the fix. edit this file according to the PR.

**Comment by Snorlax104** [comment]
Yeah it worked.Thanks dude!
